version: "3.9"
services:
  frontend:
    build:
      context: frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/project
      - /project/node_modules
  backend:
    build:
      context: backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/project-api