version: '4'
services:
  frontend:
    build: 
      context: frontend
    image: frontend-image
    ports:
      - "4200:4200"
      - "8080:80"
    volumes:
      - ./frontend:/project
      - /project/node_modules

  backend:
    build:
      context: backend
    image: backend-image
    ports:
      - 5000:5000
    volumes:
      - ./backend:/project-api
