version: '3.9'
services:
  frontend:
    build: 
      context: frontend
    image: frontend-image
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/project
      - /project/node_modules

  backend:
    build:
      context: backend
    image: backend-image
    ports:
      - 5000:5000
    volumes:
      - ./backend:/project-api
    devices:
      - /dev/video0:/dev/video0 #for Linux video capture
      - /dev/video0:/dev/video1

